//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaquetaTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NombreUsuario { get; set; }
        public bool Pagado { get; set; }
        public string Referencia { get; set; }

        public List<ProductoDTO> Productos { get; set; }
    }
}
