//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaquetaTienda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Pedido
    {
        public int Id { get; set; }
        public System.TimeSpan Fecha { get; set; }
        public string NombreUsuario { get; set; }
        public bool Pagado { get; set; }
        public string Referencia { get; set; }

        [NotMapped]
        public List<ProductoDTO> productos { get; set; }
    }
}
